services:
  games:
    image: jorgemartinezpizarro/games:latest
    restart: always
    ports:
      - ${PORT}:3000
    environment:
      - DEV_PORT=${DEV_PORT}
      - PORT=${PORT}
      - DEV_PORT=${DEV_PORT}
      - NEXTCLOUD_URL=${NEXTCLOUD_URL}
      - NEXT_PUBLIC_ENABLE_LOGIN=${NEXT_PUBLIC_ENABLE_LOGIN}
      - NEXT_PUBLIC_CHESS_URL=${NEXT_PUBLIC_CHESS_URL}
      - NEXT_PUBLIC_WORD_URL=${NEXT_PUBLIC_WORD_URL}
    volumes:
      - ./cache/audio/:/app/cache/audio
  wordlist:
    image: jorgemartinezpizarro/wordlist:latest
    # Exposed to comunicate node, remove later to use docker network communication
    ports:
      - 1009:5000
    volumes:
      - ./cache/audio/:/app/audio
  stockfish:
    image: jorgemartinezpizarro/stockfish:latest
    # Exposed to comunicate node, remove later to use docker network communication
    ports:
      - 1007:8080