services:
  games:
    image: jorgemartinezpizarro/games:latest
    restart: always
    # Exposed locally to communicate with nginx
    ports:
      - 127.0.0.1:${PORT}:${PORT}
    environment:
      - PORT=${PORT}
      - DEV_PORT=${DEV_PORT}
      - NEXTCLOUD_URL=${NEXTCLOUD_URL}
      - NEXT_PUBLIC_ENABLE_LOGIN=${NEXT_PUBLIC_ENABLE_LOGIN}
      - NEXT_PUBLIC_CHESS_URL=http://stockfish:8080
      - NEXT_PUBLIC_WORD_URL=http://wordlist:5000
    volumes:
      - ./cache/audio/:/app/cache/audio
      - ./cache/database/:/app/cache/database
  wordlist:
    image: jorgemartinezpizarro/wordlist:latest
    # Exposed locally to comunicate with node
    ports:
      - 127.0.0.1:${WORDLIST_PORT:-1009}:5000
    volumes:
      - ./cache/audio/:/app/audio
  stockfish:
    image: jorgemartinezpizarro/stockfish:latest
    # Exposed locally to comunicate with node
    ports:
      - 127.0.0.1:${STOCKFISH_PORT:-1007}:8080